#requires -Version 5.1
<#
.SYNOPSIS
    One-shot bootstrap installer for the pwsh-profile repo.
.DESCRIPTION
    Installs git if missing (via winget), clones this repo to
    %LOCALAPPDATA%\pwsh-profile, and writes a small stub to $PROFILE that
    loads the cloned profile.ps1.

    Run on a fresh PC with:
        irm https://raw.githubusercontent.com/b8usap/pwsh-profile/main/bootstrap.ps1 | iex
#>

$ErrorActionPreference = 'Stop'

$REPO_URL   = 'https://github.com/b8usap/pwsh-profile.git'
$CLONE_PATH = "$env:LOCALAPPDATA\pwsh-profile"

# 1. Ensure git is available
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "git not found. Installing via winget..." -ForegroundColor Yellow
    if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
        throw "winget not available either. Install Git for Windows manually from https://git-scm.com, then re-run this script."
    }
    winget install Git.Git --silent --accept-source-agreements --accept-package-agreements
    # Refresh PATH so git is usable immediately in this session
    $env:PATH = [Environment]::GetEnvironmentVariable('PATH','Machine') + ';' +
                [Environment]::GetEnvironmentVariable('PATH','User')
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw "winget reported success but git is still not on PATH. Open a new shell and re-run."
    }
}

# 2. Clone or update the repo
if (Test-Path $CLONE_PATH) {
    Write-Host "Repo already at $CLONE_PATH — running git pull." -ForegroundColor Cyan
    git -C $CLONE_PATH pull --ff-only
} else {
    Write-Host "Cloning $REPO_URL -> $CLONE_PATH" -ForegroundColor Cyan
    git clone $REPO_URL $CLONE_PATH
}

# 3. Ensure $PROFILE's directory exists
$profileDir = Split-Path -Parent $PROFILE
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# 4. Back up any existing $PROFILE before overwriting
if (Test-Path $PROFILE) {
    $backup = "$PROFILE.bak.$(Get-Date -Format yyyyMMdd-HHmmss)"
    Copy-Item $PROFILE $backup
    Write-Host "Existing `$PROFILE backed up to:" -ForegroundColor DarkGray
    Write-Host "  $backup" -ForegroundColor DarkGray
}

# 5. Write the stub
$stub = @'
# pwsh-profile stub — auto-generated by bootstrap.ps1
# Real profile lives at $realProfile. Edit there (or use `epr`), not here.

$repoRoot    = "$env:LOCALAPPDATA\pwsh-profile"
$realProfile = "$repoRoot\profile.ps1"

if (-not (Test-Path $realProfile)) {
    Write-Host "pwsh-profile not found at $repoRoot." -ForegroundColor Yellow
    Write-Host "Re-bootstrap with:" -ForegroundColor Yellow
    Write-Host "  irm https://raw.githubusercontent.com/b8usap/pwsh-profile/main/bootstrap.ps1 | iex" -ForegroundColor DarkGray
    return
}

# Throttled background pull: at most once per 24h. Runs in a job so it
# never blocks shell startup; failures are silent.
$pullStamp = "$repoRoot\.last-pull"
if (-not (Test-Path $pullStamp) -or
    (Get-Item $pullStamp).LastWriteTime -lt (Get-Date).AddDays(-1)) {
    try {
        Start-Job { git -C $using:repoRoot pull --ff-only 2>&1 } | Out-Null
        New-Item $pullStamp -Force | Out-Null
    } catch {}
}

. $realProfile
'@

Set-Content -Path $PROFILE -Value $stub -Encoding UTF8

Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host " pwsh-profile installed!" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host " Repo: $CLONE_PATH" -ForegroundColor White
Write-Host " Stub: $PROFILE" -ForegroundColor White
Write-Host ""
Write-Host " Open a NEW PowerShell session to load the profile." -ForegroundColor Yellow
Write-Host " First launch will run first-time setup (winget installs)." -ForegroundColor DarkGray
Write-Host "================================================================" -ForegroundColor Green
